### ISSUE TITLE
app-misc/zigbee2mqtt overwrites configuration file on update

### ISSUE THREAD

**Issue by daviessm** [inode64/inode64-overlay#10]
app-misc/zigbee2mqtt stores its data files in /var/lib/zigbee2mqtt but by default this is not protected by CONFIG_PROTECT and the users' configuration.yaml will get overwritten with the template file on every update.

According to https://devmanual.gentoo.org/general-concepts/config-protect/index.html this can be overridden by ebuilds.

**Comment by inode64** [comment]
Thank you very much, I was already using CONFIG PROTECT but there was a problem with the substitution of the PN variable

**Comment by daviessm** [comment]
Hmm, the update to 1.31.0 today clobbered my configuration.yaml again.

**Comment by inode64** [comment]
I forgot to tell you that before updating you will check that the file /etc/env.d/90zigbee2mqtt contains CONFIG_PROTECT="/var/lib/zigbee2mqtt"

If you look now you will have the variable correctly
If not, even if you have corrected the problem, Gentoo will use the old file
Check it and tell me

**Comment by daviessm** [comment]
Yep it's there now.
