### ISSUE TITLE
inode64-overlay/media-video  /davinci-resolve-studio/ 18.5 don't start

### ISSUE THREAD

**Issue by christophey2k** [inode64/inode64-overlay#11]
hi, when i start 18.5 with : 
$ LD_PRELOAD=/usr/lib64/libglib-2.0.so ./resolve

Have the splash screen that say FairLight Loading but after few sec, no response and must click to "kill" Davinci Resolve Studio...
the log say : missing files...
$ cat /home/christophe/.local/share/DaVinciResolve/logs/ResolveDebug.txt
...
/opt/resolve/bin/BlackmagicRawAPI/libBlackmagicRawAPI.so: cannot open shared object file: No such file or directory
/opt/resolve/bin/libBlackmagicRawAPI.so: cannot open shared object file: No such file or directory
0x7f26f80b2180 | Main                 | INFO  | 2023-08-15 23:57:16,756 | Show splash screen message: Chargement de Fairlight
0x7f257f7f2680 | IO                   | INFO  | 2023-08-15 23:57:16,758 | IO codec initialization completed in 2 ms.
0x7f25207c5680 | DVIP                 | INFO  | 2023-08-15 23:57:16,765 | Created OpenCL context for devices gpu:6090307e.a0aa77a0
...
i don't know if anybody have an idea...
Thanks

**Comment by inode64** [comment]
I already solved the problem of libglib-2.0.so and it is not necessary to add LD_PRELOAD

Try to run with the absolute path with the following:

**/opt/resolve/bin/resolve**

it works correctly for me.
it also happens sometimes that Davinci does not start and it hangs with the welcome screen, you cut it and run it again and then it starts correctly.

**Comment by christophey2k** [comment]
18.5 never start for me ...
i erase all files and configuration (i only keep licence files) and reinstall new one with 18.5.1
with : 
# emerge --ask --quiet --verbose davinci-resolve-studio
[ebuild   R   ~] media-video/davinci-resolve-studio-18.5.1::inode64-overlay  USE="-bundled-libs -developer" VIDEO_CARDS="amdgpu -nvidia"

emerge OK, but when i start DRS-18.5.1
have this error ...

$ /opt/resolve/bin/resolve
/opt/resolve/bin/resolve: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

(have dev-libs/openssl-3.0.9-r2 installed)
# ls -la /usr/lib64/libssl*
lrwxrwxrwx 1 root root     11 26 août  20:30 /usr/lib64/libssl.so -> libssl.so.3
-rwxr-xr-x 1 root root 679752 26 août  20:30 /usr/lib64/libssl.so.3
-rwxr-xr-x 1 root root 419144 30 juil. 09:52 /usr/lib64/libssl3.so

if i do this (for test)
# ln -s /usr/lib64/libssl.so /usr/lib64/libssl.so.1.1
and i restart Davinci Resolve Studio

$ /opt/resolve/bin/resolve
have  this other error
$ /opt/resolve/bin/resolve: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory...

**Comment by inode64** [comment]
Ok, enable bundled-libs to solve it

I still use openssl 1.1 and internally it also uses it
I think I'll have to disable bundled-libs in the new revision because it has a lot of dependencies.

**Comment by christophey2k** [comment]
Hi, enable "bundled-libs" do not solve it... do not start...

```
if i try to emerge with USE="bundled-libs" have a splash screen but the same first error have on 18.5
and last log lines are

/usr/lib64/libc.so.6(+0x8696a) [0x7f5fb4ead96a]
/usr/lib64/libc.so.6(+0x1086ac) [0x7f5fb4f2f6ac]
Signal Number = 6

================================
0x7f5fb5220f80 | Fairlight | INFO | 2023-08-26 21:20:42,851 | 00.00.00.200(000): Running Fairlight (2b918e161f664390e9eabb8ab32d09f2d61229bc)
0x7f5fb5220f80 | FairlightLoader | INFO | 2023-08-26 21:20:42,851 | Fairlight lib initialized in 201 ms.
0x7f5dba823680 | UI.GLContext | INFO | 2023-08-26 21:20:42,851 | Creating shared OpenGL context for this thread (3 total).
0x7f5dba823680 | DVIP | INFO | 2023-08-26 21:20:42,852 | Re-using OpenCL context for devices gpu:6090307e.a0aa77a0
```

**Comment by inode64** [comment]
show your emerge info

**Comment by christophey2k** [comment]
Hi, today have updated my gentoo (i do update one per week at minimum) and ....
have new kernel ok, and new rocm-opencl... and now DRS start !!!!

```
# emerge --sync
# emerge --ask --quiet --update --deep --with-bdeps=y --newuse --verbose-conflicts @world
```

completed emerge (1 of 9) sys-libs/libxcrypt-4.4.36
completed emerge (2 of 9) net-misc/whois-5.5.17-r1
completed emerge (3 of 9) media-libs/glew-2.2.0
completed emerge (4 of 9) sys-kernel/gentoo-sources-6.5.1
completed emerge (5 of 9) dev-libs/rocm-device-libs-5.5.1
completed emerge (6 of 9) dev-libs/roct-thunk-interface-5.5.1
completed emerge (7 of 9) dev-libs/rocr-runtime-5.5.1
completed emerge (8 of 9) dev-libs/rocm-comgr-5.5.1
completed emerge (9 of 9) dev-libs/rocm-opencl-runtime-5.5.1

`# cat /etc/portage/package.use`
<--->
media-video/davinci-resolve-studio bundled-libs doc
<--->

`# emerge --ask --quiet --verbose media-video/davinci-resolve-studio`
[ebuild   R   ] media-video/davinci-resolve-studio-18.5.1  USE="bundled-libs* -developer" VIDEO_CARDS="amdgpu -nvidia"


```
$ /opt/resolve/bin/resolve
$ cat /home/christophe/.local/share/DaVinciResolve/logs/ResolveDebug.txt
```
--->
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (UI).
log4cxx: Please initialize the log4cxx system properly.
18.5.1.0006 Linux/Clang x86_64
Main thread starts: 41423F80
0x7f7a41423f80 | Undefined            | INFO  | 2023-09-03 12:50:52,099 | --------------------------------------------------------------------------------
0x7f7a41423f80 | Undefined            | INFO  | 2023-09-03 12:50:52,099 | Loaded log config from /home/christophe/.local/share/DaVinciResolve/configs/log-conf.xml
0x7f7a41423f80 | Undefined            | INFO  | 2023-09-03 12:50:52,099 | --------------------------------------------------------------------------------
FusionScript Server [19835] Started
Host 'Resolve' [19453] Added
Host 'Resolve' Removed
FusionScript Server [19835] Terminated
--->

And Davinci Resolve Studio start correctly , i do not have time to work with today but it run ...
with bundled-libs flags without this
have the error message :

`$ /opt/resolve/bin/resolve`
/opt/resolve/bin/resolve: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

and this is my # emerge --info
`# emerge --info
Portage 3.0.49 (python 3.11.5-final-0, default/linux/amd64/17.1/systemd/merged-usr, gcc-12, glibc-2.37-r3, 6.5.1-gentoo x86_64)
=================================================================
System uname: Linux-6.5.1-gentoo-x86_64-AMD_Ryzen_9_7950X3D_16-Core_Processor-with-glibc2.37
KiB Mem:    65572252 total,  43985956 free
KiB Swap:    3802108 total,   3802108 free
Timestamp of repository gentoo: Sun, 03 Sep 2023 08:00:01 +0000
Head commit of repository gentoo: e3fc0f27fe4e4f70a9a8030e5b256482afca3ebf
Timestamp of repository inode64-overlay: Wed, 30 Aug 2023 14:31:51 +0000
Head commit of repository inode64-overlay: e9f051c9b59701998603dfba82e283b805bf6c1a

sh bash 5.1_p16-r6
ld GNU ld (Gentoo 2.40 p5) 2.40.0
app-misc/pax-utils:        1.3.5::gentoo
app-shells/bash:           5.1_p16-r6::gentoo
dev-java/java-config:      2.3.1-r1::gentoo
dev-lang/perl:             5.38.0-r1::gentoo
dev-lang/python:           2.7.18_p16-r1::gentoo, 3.9.18::gentoo, 3.10.13::gentoo, 3.11.5::gentoo
dev-lang/rust:             1.69.0-r1::gentoo
dev-util/cmake:            3.26.5-r2::gentoo
dev-util/meson:            1.1.1::gentoo
sys-apps/baselayout:       2.14::gentoo
sys-apps/sandbox:          2.37::gentoo
sys-apps/systemd:          253.6::gentoo
sys-devel/autoconf:        2.13-r7::gentoo, 2.71-r6::gentoo
sys-devel/automake:        1.16.5-r1::gentoo
sys-devel/binutils:        2.40-r5::gentoo
sys-devel/binutils-config: 5.5::gentoo
sys-devel/clang:           15.0.7-r3::gentoo, 16.0.6::gentoo
sys-devel/gcc:             12.3.1_p20230526::gentoo
sys-devel/gcc-config:      2.11::gentoo
sys-devel/libtool:         2.4.7-r1::gentoo
sys-devel/lld:             15.0.7::gentoo, 16.0.6::gentoo
sys-devel/llvm:            15.0.7-r3::gentoo, 16.0.6::gentoo
sys-devel/make:            4.4.1-r1::gentoo
sys-kernel/linux-headers:  6.1::gentoo (virtual/os-headers)
sys-libs/glibc:            2.37-r3::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    volatile: False
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts: 
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-jobs: 1

inode64-overlay
    location: /var/db/repos/inode64-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/inode64-overlay.git
    masters: gentoo
    volatile: False

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=znver3 -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -msse4a -mno-fma4 -mno-xop -mfma -mavx512f -mbmi -mbmi2 -maes -mpclmul -mavx512vl -mavx512bw -mavx512dq -mavx512cd -mno-avx512er -mno-avx512pf -mavx512vbmi -mavx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mavx512vpopcntdq -mavx512vbmi2 -mgfni -mvpclmulqdq -mavx512vnni -mavx512bitalg -mavx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mclwb -mclzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mmwaitx -mno-pconfig -mpku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mrdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -mno-sgx -msha -mshstk -mno-tbm -mno-tsxldtrk -mvaes -mno-waitpkg -mwbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=1024 -mtune=znver3 -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt /var/bind"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d"
CXXFLAGS="-march=znver3 -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -msse4a -mno-fma4 -mno-xop -mfma -mavx512f -mbmi -mbmi2 -maes -mpclmul -mavx512vl -mavx512bw -mavx512dq -mavx512cd -mno-avx512er -mno-avx512pf -mavx512vbmi -mavx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mavx512vpopcntdq -mavx512vbmi2 -mgfni -mvpclmulqdq -mavx512vnni -mavx512bitalg -mavx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mclwb -mclzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mmwaitx -mno-pconfig -mpku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mrdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -mno-sgx -msha -mshstk -mno-tbm -mno-tsxldtrk -mvaes -mno-waitpkg -mwbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=1024 -mtune=znver3 -O2 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-march=znver3 -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -msse4a -mno-fma4 -mno-xop -mfma -mavx512f -mbmi -mbmi2 -maes -mpclmul -mavx512vl -mavx512bw -mavx512dq -mavx512cd -mno-avx512er -mno-avx512pf -mavx512vbmi -mavx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mavx512vpopcntdq -mavx512vbmi2 -mgfni -mvpclmulqdq -mavx512vnni -mavx512bitalg -mavx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mclwb -mclzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mmwaitx -mno-pconfig -mpku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mrdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -mno-sgx -msha -mshstk -mno-tbm -mno-tsxldtrk -mvaes -mno-waitpkg -mwbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=1024 -mtune=znver3 -O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=znver3 -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -msse4a -mno-fma4 -mno-xop -mfma -mavx512f -mbmi -mbmi2 -maes -mpclmul -mavx512vl -mavx512bw -mavx512dq -mavx512cd -mno-avx512er -mno-avx512pf -mavx512vbmi -mavx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mavx512vpopcntdq -mavx512vbmi2 -mgfni -mvpclmulqdq -mavx512vnni -mavx512bitalg -mavx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mclwb -mclzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mmwaitx -mno-pconfig -mpku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mrdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -mno-sgx -msha -mshstk -mno-tbm -mno-tsxldtrk -mvaes -mno-waitpkg -mwbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=1024 -mtune=znver3 -O2 -pipe"
GENTOO_MIRRORS="ftp://ftp.free.fr/mirrors/ftp.gentoo.org/ http://gentoo.modulix.net/gentoo/ http://gentoo.mirrors.ovh.net/gentoo-distfiles/ rsync://ftp-stud.hs-esslingen.de/gentoo/"
LANG="fr_FR.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LEX="flex"
LINGUAS="fr"
MAKEOPTS="-j32"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/bash"
USE="\ a52 aac acl acpi alsa amd64 bcmath bluetooth branding bzip2 cairo caps cdda cddb cdinstall cdparanoia cdr cgi clamav cli crypt css ctype cups dbus dga dri dts dv dvd dvdr egl encode exif fbcon ffmpeg fftw flac fortran gallium gd gdbm geoip gif glamor gnome gnome-keyring gnutls gphoto2 gpm gtk hddtemp iconv ieee1394 imagemagick imap imlib inifile introspection ipv6 jack javascript jpeg jpeg2k lame ldap libnotify libsamplerate libtirpc libwww lm_sensors lzma lzo maildir matroska mikmod mmap mozilla mp3 mp4 mpeg mplayer multilib musepack musicbrainz mysql mysqli nas ncurses networkmanager nls nntp nptl nsplugin offensive ogg openal opencl openexr openmp oss pam pcre pdf perl php plasma png policykit posix postscript quicktime raw rdesktop readline rss samba sasl scanner sctp sdl seccomp session sharedmem simplexml smp sockets sound speex spell sqlite ssl suid svg symlink syslog systemd tcpd test-rust theora tiff tk tokenizer truetype udev udisks unicode upnp upnp-av upower usb v4l vaapi vhosts videos vim-syntax vnc vorbis wavpack wayland webkit wifi wmf wxwidgets x264 x265 xattr xcb xcomposite xinerama xinetd xml xmlrpc xosd xpm xv xvid zeroconf zlib" ABI_X86="64" ADA_TARGET="gnat_2021" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev" KERNEL="linux" L10N="fr" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php8-1" POSTGRES_TARGETS="postgres15" PYTHON_SINGLE_TARGET="python3_11" PYTHON_TARGETS="python3_11" RUBY_TARGETS="ruby31" VIDEO_CARDS="amdgpu radeonsi radeon fbdev" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS`

Thank you for the big job

**Comment by inode64** [comment]
If using -bundled-libs , media-video/davinci-resolve-studio needs openssl 1.1.x
Another problem was amdgpu, I couldn't make it work only with AMD and in the end I switched to an NVIDIA card. If it works for you now it's because it needs a version of dev-libs/rocm-opencl-runtime 5.5.1 or higher to work correctly

**Comment by inode64** [comment]
fix in https://github.com/inode64/inode64-overlay/commit/5b6a9765501f3eff3d23c338f827347df4fe55a9

**Comment by inode64** [comment]
I have updated the dependencies and included the option to search for dependencies in binaries and libraries that may be missing

use "revdep-rebuild -v -i" from app-portage/gentoolkit to check that everything is correct and tell me if there are any errors

all the best

**Comment by christophey2k** [comment]
# emerge --unmerge davinci-resolve-sstudio
# emerge --sync

Action: sync for repo: gentoo, returned code = 0
Action: sync for repo: inode64-overlay, returned code = 0

# emerge --ask --quiet --verbose davinci-resolve-studio
[ebuild  N    ] media-video/davinci-resolve-studio-18.5.1  USE="bundled-libs -developer" VIDEO_CARDS="amdgpu -nvidia" 

Would you like to merge these packages? [Yes/No] y
>>> Verifying ebuild manifests
>>> Running pre-merge checks for media-video/davinci-resolve-studio-18.5.1
 * Checking for at least 20 GiB disk space at "/var/tmp/portage/media-video/davinci-resolve-studio-18.5.1/temp" ...                   [ ok ]
>>> Emerging (1 of 1) media-video/davinci-resolve-studio-18.5.1::inode64-overlay
>>> Installing (1 of 1) media-video/davinci-resolve-studio-18.5.1::inode64-overlay
>>> Recording media-video/davinci-resolve-studio in "world" favorites file...
>>> Completed (1 of 1) media-video/davinci-resolve-studio-18.5.1::inode64-overlay
>>> Jobs: 1 of 1 complete                           Load avg: 1.46, 0.89, 0.87
# revdep-rebuild -v -i
 * This is the new python coded version
 * Please report any bugs found using it.
 * The original revdep-rebuild script is installed as revdep-rebuild.sh
 * Please file bugs at: https://bugs.gentoo.org/
 * Collecting system binaries and libraries
 * Collecting dynamic linking information
 * Scanning files
 * Checking dynamic linking consistency

Your system is consistent

# emerge --ask --quiet --verbose @preserved-rebuild

Nothing to merge; quitting.


No problems with USE="bundled-libs"

**Comment by inode64** [comment]
run revdep-rebuild -v -i

**Comment by christophey2k** [comment]
i try this before unmerge, after re-emerge, and i try with and without USE="bundled-libs"

` # revdep-rebuild -v -i`
 * This is the new python coded version
 * Please report any bugs found using it.
 * The original revdep-rebuild script is installed as revdep-rebuild.sh
 * Please file bugs at: https://bugs.gentoo.org/
 * Collecting system binaries and libraries
 * Collecting dynamic linking information
 * Scanning files
 * Checking dynamic linking consistency

Your system is consistent

**Comment by inode64** [comment]
oops. I had made a mistake when renaming the version
Update again to media-video/davinci-resolve-studio-18.5.1-r2 and do revdep-rebuild -v -i again

**Comment by inode64** [comment]
With the latest version of Davinci it already works correctly for you?

**Comment by inode64** [comment]
We close issue, since there is a problem in rocm 5.5.7
