### ISSUE TITLE
Davinci resolve studio 18.6 - start with segfault

### ISSUE THREAD

**Issue by christophey2k** [inode64/inode64-overlay#15]
Hello,
DRS 18.6 segfault at run

`$ ./resolve

ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
log4cxx: No appender could be found for logger (UI).
log4cxx: Please initialize the log4cxx system properly.
18.6.0.0009 Linux/Clang x86_64
Main thread starts: 5DA3F000
0x7f7b5da3f000 | Undefined            | INFO  | 2023-11-12 18:06:02,356 | --------------------------------------------------------------------------------
0x7f7b5da3f000 | Undefined            | INFO  | 2023-11-12 18:06:02,356 | Loaded log config from /home/christophe/.local/share/DaVinciResolve/configs/log-conf.xml
0x7f7b5da3f000 | Undefined            | INFO  | 2023-11-12 18:06:02,356 | --------------------------------------------------------------------------------
Erreur de segmentation (core dumped)
`
`$ cat /home/christophe/.local/share/DaVinciResolve/logs/ResolveDebug.txt
0x7f7b5da3f000 | Main                 | INFO  | 2023-11-12 18:06:02,356 | Running DaVinci Resolve Studio v18.6.0.0009 (Linux/Clang x86_64)
0x7f7b5da3f000 | Main                 | INFO  | 2023-11-12 18:06:02,356 | BMD_BUILD_UUID 4b5bd069-4606-4632-954b-7ecf318f8834
0x7f7b5da3f000 | Main                 | INFO  | 2023-11-12 18:06:02,356 | BMD_GIT_COMMIT 2541dac8b8ea4bd08de600b58edcb7d95aa657bc
0x7f7b5da3f000 | GPUDetect            | INFO  | 2023-11-12 18:06:02,356 | Starting GPUDetect 1.2_5-a6
`

When i try revdep-rebuild # revdep-rebuild -v -i
i can see probleme with cuda, but have amd graphics card and compile with -nvidia
i think the -nvidia flag do not work

` * This is the new python coded version
 * Please report any bugs found using it.
 * The original revdep-rebuild script is installed as revdep-rebuild.sh
 * Please file bugs at: https://bugs.gentoo.org/
 * Collecting system binaries and libraries
 * Collecting dynamic linking information
 * Scanning files
 * Checking dynamic linking consistency
 * Broken files that require: libcuda.so.1 (64 bits)
	* /opt/resolve/BlackmagicRAWPlayer/BlackmagicRawAPI/libDecoderCUDA.so
	* /opt/resolve/BlackmagicRAWSpeedTest/BlackmagicRawAPI/libDecoderCUDA.so
	* /opt/resolve/libs/libDecoderCUDA.so
 * Assign files to packages
	* /opt/resolve/libs/libDecoderCUDA.so -> media-video/davinci-resolve-studio-18.6
	* /opt/resolve/BlackmagicRAWSpeedTest/BlackmagicRawAPI/libDecoderCUDA.so -> media-video/davinci-resolve-studio-18.6
	* /opt/resolve/BlackmagicRAWPlayer/BlackmagicRawAPI/libDecoderCUDA.so -> media-video/davinci-resolve-studio-18.6

emerge --verbose --oneshot --complete-graph=y media-video/davinci-resolve-studio:0

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 3.16 s.

[ebuild   R   ~] media-video/davinci-resolve-studio-18.6::inode64-overlay  USE="bundled-libs -developer" VIDEO_CARDS="amdgpu -nvidia" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB
`

**Comment by inode64** [comment]
If until now it was working correctly for you, it will be an update to another application that has generated the problem.
Send me the list of changes in Gentoo since the last time it worked for you with:

<pre>
genlop -u
</pre>

**Comment by christophey2k** [comment]
This is a big list
Have same error with DARKTABLE but i don't remember when that stop to run like DRS

[genlop-u-sep-nov_2023.txt](https://github.com/inode64/inode64-overlay/files/13341739/genlop-u-sep-nov_2023.txt)

**Comment by christophey2k** [comment]
I can resolve the segfault and have my gentoo update at 18/11/2023

Need AMD driver at version  5.5.1

# nano /etc/portage/package.accept_keywords
<--->
...
# Pilote libre OpenCL pour AMD GPU
=dev-libs/rocm-opencl-runtime-5.5.1 ~amd64
=dev-libs/rocr-runtime-5.5.1 ~amd64
=dev-libs/rocm-comgr-5.5.1 ~amd64
=dev-libs/rocm-device-libs-5.5.1 ~amd64
=dev-util/rocm-cmake-5.5.1 ~amd64
=dev-libs/roct-thunk-interface-5.5.1 ~amd64

=sys-devel/clang-17.0.5 ~amd64
=sys-devel/clang-common-17.0.5 ~amd64
=sys-devel/clang-runtime-17.0.5 ~amd64
=sys-devel/clang-toolchain-symlinks-17 ~amd64
=sys-libs/compiler-rt-17.0.5 ~amd64
=sys-libs/compiler-rt-sanitizers-17.0.5 ~amd64
=sys-devel/llvm-17.0.5 ~amd64
=sys-devel/llvm-toolchain-symlinks-17 ~amd64
=sys-libs/libomp-17.0.5 ~amd64
=sys-devel/llvmgold-17 ~amd64
=sys-devel/lld-17.0.5 ~amd64
=sys-devel/lld-toolchain-symlinks-17 ~amd64

# Overlay DAVINCI RESOLVE
>=media-video/davinci-resolve-studio-18.5 ~amd64
...
<--->
#  emerge --ask --quiet --update --deep --with-bdeps=y --newuse @world
# emerge --ask --quiet --verbose davinci-resolve-studio
--->
[ebuild   R   ] media-video/davinci-resolve-studio-18.6  USE="bundled-libs -developer" VIDEO_CARDS="amdgpu -nvidia"
--->
# emerge --depclean
# emerge --ask --quiet --verbose @module-rebuild

But if i try
# revdep-rebuild -ib
--->
 This is the new python coded version
 * Please report any bugs found using it.
 * The original revdep-rebuild script is installed as revdep-rebuild.sh
 * Please file bugs at: https://bugs.gentoo.org/
 * Collecting system binaries and libraries
 * Collecting dynamic linking information
 * Scanning files
 * Checking dynamic linking consistency
 * Broken files that require: libcuda.so.1 (64 bits)
	* /opt/resolve/BlackmagicRAWPlayer/BlackmagicRawAPI/libDecoderCUDA.so
	* /opt/resolve/BlackmagicRAWSpeedTest/BlackmagicRawAPI/libDecoderCUDA.so
	* /opt/resolve/libs/libDecoderCUDA.so
 * Assign files to packages
	* /opt/resolve/libs/libDecoderCUDA.so -> media-video/davinci-resolve-studio-18.6
	* /opt/resolve/BlackmagicRAWSpeedTest/BlackmagicRawAPI/libDecoderCUDA.so -> media-video/davinci-resolve-studio-18.6
	* /opt/resolve/BlackmagicRAWPlayer/BlackmagicRawAPI/libDecoderCUDA.so -> media-video/davinci-resolve-studio-18.6

emerge --pretend --verbose --oneshot --complete-graph=y media-video/davinci-resolve-studio:0
--->
But after merge DRS if i re run revdep-rebuild command
it found the same error and want to re compile davinci...

**Comment by inode64** [comment]
I think I had solved it in version 18.6

to require at least [>=dev-libs/rocm-opencl-runtime-5.5.1](https://github.com/inode64/inode64-overlay/blob/main/media-video/davinci-resolve-studio/davinci-resolve-studio-18.6.ebuild?#L126)

I have also updated the Danvici

Now I only use Nvidia, not AMD. If you have another problem, let me know or if everything is correct, we will close the task.
all the best

**Comment by inode64** [comment]
With the latest version of Davinci it already works correctly for you?

**Comment by christophey2k** [comment]
hi, good for me !
With full updated Gentoo at this day with kernel 6.6.5 and rocm v5.5.1 Davinci Resolve Studio 18.6.4 run normally.

Note1: with rocm V5.5.7 , segfault at startup.

Note2: the only problem is performance drop with the "Blackmagic RAW speed test" the OpenCL GPU performance, is lower than have with older OpenCL driver... before 5.5.1 have full green check point at all resolution now GPU can't handle >=6k/8K@50/60 FPS , max is at 6k@30 (GPU is AMD RX6900XT)

![BlackMagicRAWSpeedTest-0912023](https://github.com/inode64/inode64-overlay/assets/3194740/5c21214e-e176-42b0-9830-9c1b9ad0fd07)

**Comment by inode64** [comment]
Ok, now I only use Nvidia, I'm trying with the new versions of Rocm and tell me, I think they will improve Rocm and solve problems, otherwise it would be to report the problem to Rocm, and then we can close this issue
Thank you
