### ISSUE TITLE
Davinci Resolve Studio V19B1 - > Davinci Control Panels Setup do not start

### ISSUE THREAD

**Issue by christophey2k** [inode64/inode64-overlay#22]
Hi,
have install the latest "Davinci Resolve Studio v19 beta 1" 
After starting the software, DRS detect my "Speed Editor" keyboard (USB connected) and ask me to upgrade the firmware
(maybe a good news for the wireless bug : under Linux never work in Bluetooth wireless mode)

![Capture d’écran du 2024-04-22 23-54-58](https://github.com/inode64/inode64-overlay/assets/3194740/b94d1e67-d8aa-47eb-9dff-d703ff0ab1e9)

But the "Davinci Control Panels Setup do not start" and i need it for upgrade firmware...

with this log file:
0x7f2a33a5b000 | SyManager.Signals    | INFO  | 2024-04-22 23:54:48,469 | Main view page is changed to 1
0x7f2a33a5b000 | UI                   | WARN  | 2024-04-22 23:54:48,469 | Failed to get auto update information.
0x7f2a33a5b000 | SyManager.Signals    | INFO  | 2024-04-22 23:54:48,494 | Main view page is changed to 17
0x7f2a33a5b000 | SyManager.Signals    | INFO  | 2024-04-22 23:54:48,539 | Main view page is changed to 17
0x7f2a33a5b000 | UI                   | INFO  | 2024-04-22 23:54:48,540 | Launching main window
0x7f2a33a5b000 | UI                   | INFO  | 2024-04-22 23:54:48,543 | Gallery pointer is changed, refreshing color gallery
0x7f2a33a5b000 | UI                   | INFO  | 2024-04-22 23:54:48,549 | Gallery pointer is changed, refreshing gallery browser
0x7f2a33a5b000 | SyManager            | INFO  | 2024-04-22 23:54:48,552 | DRSE (14B5A33A8B7F411C8CB2F7759E0D8ED7) firmware update available (b13612e5 to 737b6186)
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
/opt/resolve/DaVinci Control Panels Setup/QtWebEngineProcess: symbol lookup error: /usr/lib64/libkrb5.so.3: undefined symbol: krb5int_c_deprecated_enctype, version k5crypto_3_MIT
/opt/resolve/DaVinci Control Panels Setup/QtWebEngineProcess: symbol lookup error: /usr/lib64/libkrb5.so.3: undefined symbol: krb5int_c_deprecated_enctype, version k5crypto_3_MIT
0x7f2a33a5b000 | SyManager.ProjectManager | INFO  | 2024-04-23 00:03:44,866 | Start saving project LAF
0x7f2a33a5b000 | DbCommon2            | INFO  | 2024-04-23 00:03:44,866 | Initializing fresh project library /home/christophe/.local/share/DaVinciResolve/Resolve Project Library/Resolve Projects/Users/guest/Projects/LAF/Project.db @ Local Database
0x7f2a33a5b000 | SyManager.ProjectManager | INFO  | 2024-04-23 00:03:45,314 | Saving project took 448 ms

**Comment by inode64** [comment]
OK thanks
It also happens to me that it doesn't update.
As soon as I have a little time I'll investigate it.

**Comment by inode64** [comment]
I think I have already found the problem, I have already been able to update the "Speed ​​Editor" 

Try it yourself and tell me

**Comment by christophey2k** [comment]
yes ... # USE="bundled-libs" emerge --ask --quiet --verbose davinci-resolve-studio 
and i can lauch the "Davinci Control Panels Setup" and update firmware of keyboard...

Bluetooth do not work for "speed editor"... have you a bluetooth working for Speed Editor under Gentoo ?

**Comment by inode64** [comment]
not at the moment, only usb
But I have seen that there are problems with new Bluetooth devices
