### ISSUE TITLE
dev-lang/php-5.6.40-r8 configure error

### ISSUE THREAD

**Issue by zen2** [inode64/inode64-overlay#23]
I try to emerge dev-lang/php:5.6 but I got a configure error:

```
checking for system library directory... lib
checking whether to enable runpaths... yes
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking for gawk... gawk
checking for bison... bison -y
checking for bison version... 3.8 (ok)
checking for re2c... re2c
checking for re2c version... 3.1 (ok)
checking whether to enable computed goto gcc extension with re2c... no
./configure: line 6381: test: too many arguments
checking whether to force non-PIC code in shared modules... no
checking whether /dev/urandom exists... yes
./configure: line 6809: syntax error near unexpected token `fi'
./configure: line 6809: `fi'
```

[config.log](https://github.com/inode64/inode64-overlay/files/15165799/config.log)
[dev-lang:php-5.6.40-r8:20240430-141843.log.gz](https://github.com/inode64/inode64-overlay/files/15165817/dev-lang.php-5.6.40-r8.20240430-141843.log.gz)

**Comment by Teddytrombone** [comment]
Same here. It seems that autoconf messes the configure script up
If I removing the line `eautoreconf` the `configure` works, but it uses the shipped configure script of course instead of rebuilding with patched configure.ac
Any chance this will be fixed?

**Comment by inode64** [comment]
Yes, I have to adapt this version for the new versions of gcc, libxml and the rest, as I have done in PHP 7.4
As soon as I have some time I apply the patches

**Comment by inode64** [comment]
I just updated PHP 5.6 to support GCC 14 as well as more backports of the new versions
Try it and tell me how it worked for you.

All the best

**Comment by Teddytrombone** [comment]
I've tested the ebuild. Compilation works, but in install phase there seems to be a problem
<pre>
>>> Install dev-lang/php-5.6.40_p20241216 into /var/tmp/portage/dev-lang/php-5.6.40_p20241216/image
make -j3 INSTALL_ROOT=/var/tmp/portage/dev-lang/php-5.6.40_p20241216/image install-build install-headers install-programs
Installing build environment:     /var/tmp/portage/dev-lang/php-5.6.40_p20241216/image/usr/lib64/php5.6/lib/build/
Installing helper programs:       /var/tmp/portage/dev-lang/php-5.6.40_p20241216/image/usr/lib64/php5.6/bin/
  program: phpize
  program: php-config
Installing man pages:             /var/tmp/portage/dev-lang/php-5.6.40_p20241216/image/usr/lib64/php5.6/man/man1/
  page: phpize.1
  page: php-config.1
Installing header files:           /var/tmp/portage/dev-lang/php-5.6.40_p20241216/image/usr/lib64/php5.6/include/php/
 * Installing SAPI: cli
sed: -e expression #1, char 39: unterminated `s' command
</pre>

and then

<pre>
 * The specific snippet of code:
 *       sed -e 's|^;include_path = ".:/php/includes".*|' 'include_path = ".:'"${EPREFIX}"'/usr/share/php'${PHP_MV}':'"${EPREFIX}"'/usr/share/php"|' -i "${phpinisrc}" || die;
 </pre>

I guess, there is something wrong with the env vars.

As soon as I have time, I can investigate further

**Comment by inode64** [comment]
Fix, thanks!

**Comment by Teddytrombone** [comment]
Compiling now works for me, thank you
