### ISSUE TITLE
app-metrics/pcp-5.3.7 wrong USE flag postgresql

### ISSUE THREAD

**Issue by Yann-Kaelig** [inode64/inode64-overlay#7]
The USE flags should be postgres. https://www.gentoo.org/support/use-flags/ 
Description could be: "Enable PCP Performance Metrics Domain Agent (PMDA) for collecting metrics about the PostgreSQL database."

**Comment by inode64** [comment]
Fix in commit #68273ea136cf494da15579d1f2f224e00f7b06fe

Thanks!!
