### ISSUE TITLE
app-emulation/cockpit-machines need app-emulation/qemu[+usbredir]

### ISSUE THREAD

**Issue by Yann-Kaelig** [inode64/inode64-overlay#9]
Currently creating a VM from cockpit fails:
**error: Failed to define domain from /tmp/tmpfedkb562 error: unsupported configuration: USB redirection is not supported by this version of QEMU** 

Compiling qemu with **usbredir** USE flag fix the issue.

**Comment by inode64** [comment]
Fix in commit #94588e31d799aaa0586a653cb519a5d074a8e989

I always use usbredir, that's why I didn't see this error
Thanks!!
